# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6392f9c536dd9245c67f7d4e5d8377743a606c43caf6ba44df5a73ccb837039e3eee9f29b13d7a39f8fdad0fa810a455817c35781e0a08a4ebfaba8024327f8
  twitter_api_key: 3dgM2GqEqTUxMbD4s9J5Hfetn
  twitter_api_secret: cTU3YekCDH3kBbpzcyM7Vdtmcf1YpmpRfY5QZAHHV8BXziiLMe

test:
  secret_key_base: b9729781cf11d5ae43c1da75a80dfdf5e7766e02a10af32c098b404ee08c5c569e4583833d72f8adce0e97c182eee12e911d563a8f77fb526d6b55179a781e31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
